### ISSUE TITLE
Schism crashes the whole system when accessing D drive on Windows 10 22H2

### ISSUE THREAD

**Issue by SolidnyWonsz** [schismtracker/schismtracker#576]
Hi, I'm trying to load in samples from my D drive, but Schism stops responding when I access it and then Windows logs me out. It doesn't happen with any other software accessing the drive, only Schism. Crystal Disk Info shows the drive's health is at 98% so it's definitely not the drive's fault

**Comment by sagamusix** [comment]
> Crystal Disk Info shows the drive's health is at 98% so it's definitely not the drive's fault

That doesn't really say anything. It's only a guess at the expected remaining lifetime of the drive based on the amount of data written to it. A drive could be at 100% health as far as Crystal Disk Info is concerned and still be in a broken state.

A user-mode application like Schism Tracker cannot cause your whole system to crash. If it's taking down your whole Windows system, that is **always** an indication of a broken driver, broken hardware or some other bug in Windows itself. It's very well possible that you don't experience the same crash with other software because it might not be exercising your drivers or hardware in the same way as Schism Tracker does.

When does the crash happen? Does it happen when opening Schism Tracker's sample / instrument browser, or does it happen when trying to load a specific sample?

**Comment by SolidnyWonsz** [comment]
It happens when I enter the root directory of my D drive and it only happens in the sample browser. The whole system doesn't crash, it just literally logs me out and I have to log in again.

**Comment by sagamusix** [comment]
That still sounds something caused by the OS itself and not necessary Schism Tracker itself. Maybe related to #506.

If have the opportunity to do so, try moving all files out of the folder you have trouble with to a temporary location. Move them back one by one, each time refreshing the sample browser, until the problem starts happening again. Once you find the file that causes the problem, it would be great if you could share it with us. It could be an issue with Media Foundation codecs.

**Comment by a11cf0** [comment]
The  same thing happens on my system when trying to visit a directory containing a 7.34 GB ZIP archive of mostly MP3 files. It seems Schism Tracker is trying to load the entire archive into RAM, because I can notice excessive memory usage with crazy swapping right before everything starts to crash. I'm running Windows 11 24H2 on a laptop with 18 GB of RAM.

**Comment by mrpapersonic** [comment]
I'm thinking maybe this is the memory mapping code (which shouldn't be reading the file, or even be doing anything in the physical memory block at all) or the newly-added EDL info reading stuff.

I'm on vacation right now but I'll attach a build with the memory mapping disabled when I get the time. :)

**Comment by mrpapersonic** [comment]
I can replicate that weird behavior even with arbitrary files, which means theres a bug in the stdio implementation. ugh

**Comment by mrpapersonic** [comment]
Ok, try out this build: [schismtracker-20250102-mingw32-x86_64.zip](https://github.com/user-attachments/files/18294267/schismtracker-20250102-mingw32-x86_64.zip)

it works well for me on Windows 10 v1809.

**Comment by a11cf0** [comment]
When opening the same directory with a large file, the latest revision is still doing crazy things on my system. Sometimes it just hangs and eventually gets killed by Windows along with other applications like explorer.exe, other times it stays responsive, but eats a lot of ram and makes random system processes crash with weird exceptions or causes GPU driver restarts. Moving the file to a different drive doesn't seem to help at all.

**Comment by mrpapersonic** [comment]
I have a dummy 15 GiB file (filled entirely with zeroes) that schism hangs on but otherwise does not cause any adverse effects. I'm not sure whats happening on your system.

**Comment by mrpapersonic** [comment]
I was actually able to reproduce this, or something similar on Windows 10 21H2 LTSC. Notably, I was downloading multiple very large zip files into the directory I pathed into that caused the entire system to bug out. The effect ended up being a completely unusable desktop (not even Ctrl-Alt-Del would work) which I had to force power off. Oddly enough the mouse cursor was still present.

I'm guessing this has something to do with ZIP archives since both cases involve these (we might have to blacklist the PKZIP magic somewhere??)

**Comment by mrpapersonic** [comment]
reproduced again, this is what gdb has to say about it:
```
#0  0x00007ffb7c6d0054 in ntdll!ZwWaitForSingleObject () from C:\Windows\SYSTEM32\ntdll.dll
(gdb) bt
#0  0x00007ffb7c6d0054 in ntdll!ZwWaitForSingleObject () from C:\Windows\SYSTEM32\ntdll.dll
#1  0x00007ffb78970f33 in WaitForSingleObjectEx () from C:\Windows\System32\KernelBase.dll
#2  0x00007ffb7354613d in MFPlat!MFCreateOOPMFTRemote () from C:\Windows\SYSTEM32\mfplat.dll
#3  0x00007ff7bfcc45b1 in win32mf_start (data=data@entry=0x5ffb30, fp=fp@entry=0x5ffbe0,
    url=0x33b57150 L"C:\\Users\\Paper\\Downloads\\vs2015.3.com_enu.iso") at ../fmt/win32mf.c:763
#4  0x00007ff7bfcc4da8 in fmt_win32mf_read_info (file=0x2c51970, fp=0x5ffbe0)
    at ../fmt/win32mf.c:862
#5  0x00007ff7bfc6c2ff in file_info_get (file=0x2c51970) at ../schism/dmoz.c:2011
#6  dmoz_filter_ext_data (file=0x2c51970) at ../schism/dmoz.c:2034
#7  0x00007ff7bfc6c399 in dmoz_fill_ext_data (file=<optimized out>) at ../schism/dmoz.c:2064
#8  0x00007ff7bfc6b7b1 in dmoz_worker () at ../schism/dmoz.c:1437
#9  0x00007ff7bfc71a75 in event_loop () at ../schism/main.c:841
#10 schism_main (argc=<optimized out>, argc@entry=1, argv=<optimized out>, argv@entry=0xe11f60)
    at ../schism/main.c:1119
#11 0x00007ff7bfcdd42a in main (argc=1, argv=0xe11f60) at ../schism/main.c:1130
(gdb)
```
Thus, this would probably be enough to fix the issue:
```diff
diff --git a/fmt/win32mf.c b/fmt/win32mf.c
index f8c0ca37..610a3042 100644
--- a/fmt/win32mf.c
+++ b/fmt/win32mf.c
@@ -760,7 +760,7 @@ static int win32mf_start(struct win32mf_data *data, slurp_t *fp, wchar_t *url)
        if (!mfbytestream_new(&data->byte_stream, fp))
                goto cleanup;

-       if (FAILED(IMFSourceResolver_CreateObjectFromByteStream(resolver, data->byte_stream, url, MF_RESOLUTION_MEDIASOURCE | MF_RESOLUTION_CONTENT_DOES_NOT_HAVE_TO_MATCH_EXTENSION_OR_MIME_TYPE | MF_RESOLUTION_READ, NULL, &object_type, &unknown_media_source)))
+       if (FAILED(IMFSourceResolver_CreateObjectFromByteStream(resolver, data->byte_stream, url, MF_RESOLUTION_MEDIASOURCE | (!url ? MF_RESOLUTION_CONTENT_DOES_NOT_HAVE_TO_MATCH_EXTENSION_OR_MIME_TYPE : 0) | MF_RESOLUTION_READ, NULL, &object_type, &unknown_media_source)))
                goto cleanup;

        if (object_type != MF_OBJECT_MEDIASOURCE)
```
